### PR TITLE
Content api python examples

### PR DESCRIPTION
**Pull request by brapel**

### CODE REVIEW

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-catalogs.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-catalogs.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C8%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711081745502528-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=c%2FcJuWO4cUDylLwp35ZYJ1IamtVtLmU5IAfHbVBuoyM%3D&st=2017-11-08T17%3A43%3A25Z&se=2017-12-09T17%3A48%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-catalogs.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-catalogs.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C8%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711081750530230-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Vtb3SuQ3QmgyYntV6B2Tm3RjIxsAoM0UnKBYhJDSpg8%3D&st=2017-11-08T17%3A48%3A31Z&se=2017-12-09T17%3A53%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brapel** [comment]
#sign-off

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/code-example-manage-catalogs.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-catalogs.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C9%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711091834594136-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=esylnYslWtjdY91V2cgga4gt5ZdP10qupARlELlYi5s%3D&st=2017-11-09T18%3A33%3A42Z&se=2017-12-10T18%3A38%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/code-example-manage-catalogs.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-catalogs.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-python-examples/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C13%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711131726141809-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VG2e6krN4lsM%2Fg0vrfLK3UBc%2B%2BEj52b5tQaitRUzMMM%3D&st=2017-11-13T17%3A22%3A43Z&se=2017-12-14T17%3A27%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brapel** [comment]
Will submit all new samples in one pr.  Closing this one.

**Pull request closed without merging**
