### PR TITLE
update ms.topic metadata value

### PR DESCRIPTION
**Pull request by v-savila**
for task 1199273

### CODE REVIEW

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/index.md](https://github.com/v-savila/BingAds-docs/blob/1199273/BingAds/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C5%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201803052320155717-151%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=L3Mr8KneuzJbAd920M7sOHLeUjiikqak9%2Bf7Bn9fyac%3D&st=2018-03-05T23%3A16%3A41Z&se=2018-04-05T23%3A21%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-savila** [comment]
#sign-off from apexprod

**Comment by cmcclister** [comment]
Hi @eric-urban please merge this PR when you can so that we can resolve the open issue (meta data update for [1199256](https://mseng.visualstudio.com/CSI/_workitems/edit/1199256)). Thank you.

**Comment by eric-urban** [comment]
@cmcclister thanks for the context. The commit to master is [here](https://github.com/MicrosoftDocs/BingAds-docs/commit/14c14ee9308523c4630b0c2a609d54dc60edc8bb).

**Pull request closed without merging**
