### PR TITLE
1170815- Update index.md

### PR DESCRIPTION
**Pull request by cmcclister**

### CODE REVIEW

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/index.md](https://github.com/cmcclister/BingAds-docs/blob/patch-1/BingAds/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C23%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201802231736313494-146%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Z7g7nDC3j2q4bOkv5GXHceqHO35n3fdqSyf5aAMpzZ0%3D&st=2018-02-23T17%3A32%3A52Z&se=2018-03-26T17%3A37%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by cmcclister** [comment]
#sign-off from apexprod also need sign-off from @v-brapel

**Comment by cmcclister** [comment]
@v-brapel and @eric-urban please configure so that a preview link is created, otherwise we cannot test these changes. Thank you.

**Comment by eric-urban** [comment]
@swhite-msft can you help here as needed?

**Comment by brapel** [comment]
These changes have been incorporated into another branch and will publish when that branch is ready to go live.

**Pull request closed without merging**
