### PR TITLE
content-api: python product and catalog code samples

### PR DESCRIPTION
**Pull request by brapel**
It feels more prudent to merge this as it is rather than waiting for hotel api python examples.  Hotels api samples can go separately in a different pr.

### CODE REVIEW

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/code-example-download-catalog-status-report.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-download-catalog-status-report.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-catalogs.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-manage-catalogs.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C16%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711161435041443-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UiydqukcUP82ladtH%2BFFzEfDIVko%2BcedqVZUSspFuhc%3D&st=2017-11-16T14%3A31%3A32Z&se=2017-12-17T14%3A36%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/code-example-download-catalog-status-report.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-download-catalog-status-report.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-catalogs.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-manage-catalogs.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C17%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711172146015171-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6ZaH5dsrU0MweWkg4WMPfJWhOlTp9Jp1WEPWTwWJSvk%3D&st=2017-11-17T21%3A43%3A50Z&se=2017-12-18T21%3A48%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/code-example-download-catalog-status-report.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-download-catalog-status-report.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-catalogs.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-manage-catalogs.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-code-samples/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C20%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711201455114668-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9QA1%2BwJwjFlkPkuikKxg0oSHsX9anE39raRdInPEaog%3D&st=2017-11-20T14%3A51%3A54Z&se=2017-12-21T14%3A56%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brapel** [comment]
The changes appear fine on the review site: https://review.docs.microsoft.com/en-us/bingads/shopping-content/code-example-manage-products?branch=content-api-code-samples

**Pull request merged**
