### PR TITLE
Content api restructure

### PR DESCRIPTION
**Pull request by brapel**
consolidated product code examples into one and redirected old files.

### CODE REVIEW

**Comment by eric-urban** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml) | :warning:Warning | | [Details](#user-content-BingAds%2Fshopping-content%2FTOC.yml)
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md) | :warning:Warning | | [Details](#user-content-BingAds%2Fshopping-content%2Fcode-examples.md)
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |

<a name="BingAds%2Fshopping-content%2FTOC.yml"></a>
### [BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml)
 - **[Warning]** Invalid file link:(~/shopping-content/code-example-get-list-product-offers.md).

<a name="BingAds%2Fshopping-content%2Fcode-examples.md"></a>
### [BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md)
 - **Line 26**: **[Warning]** Invalid file link:(~/shopping-content/code-example-get-list-product-offers.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711072100260836-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ItuWQbhQHDQPylEmTm%2FHKzC9zzvVFnD1ZiTp76MDXT4%3D&st=2017-11-07T20%3A57%3A20Z&se=2017-12-08T21%3A02%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md) | :warning:Warning | | [Details](#user-content-BingAds%2Fshopping-content%2Fmanage-products.md)
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |

<a name="BingAds%2Fshopping-content%2Fmanage-products.md"></a>
### [BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md)
 - **Line 47**: **[Warning]** Illegal link: `[Getting a Product Offer](../shopping-content/code-examples.md#get)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named get.
 - **Line 68**: **[Warning]** Illegal link: `[Getting a List of Product Offers](../shopping-content/code-examples.md#list)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named list.
 - **Line 83**: **[Warning]** Illegal link: `[Deleting a Product Offer](../shopping-content/code-examples.md#delete)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named delete.
 - **Line 150**: **[Warning]** Illegal link: `[Inserting a Product Offer](../shopping-content/code-examples.md#insert)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named insert.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711072110182927-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Wle0CH8xwdRKGA40mT9nP5b9ou1MlVibLEa3i7zAGCQ%3D&st=2017-11-07T21%3A08%3A52Z&se=2017-12-08T21%3A13%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md) | :warning:Warning | | [Details](#user-content-BingAds%2Fshopping-content%2Fmanage-products.md)
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |

<a name="BingAds%2Fshopping-content%2Fmanage-products.md"></a>
### [BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md)
 - **Line 47**: **[Warning]** Illegal link: `[Getting a Product Offer](../shopping-content/code-examples.md#get)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named get.
 - **Line 68**: **[Warning]** Illegal link: `[Getting a List of Product Offers](../shopping-content/code-examples.md#list)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named list.
 - **Line 83**: **[Warning]** Illegal link: `[Deleting a Product Offer](../shopping-content/code-examples.md#delete)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named delete.
 - **Line 150**: **[Warning]** Illegal link: `[Inserting a Product Offer](../shopping-content/code-examples.md#insert)` -- missing bookmark. The file shopping-content/code-examples.md doesn&#39;t contain a bookmark named insert.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711072117290211-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AEfI5Z4HkHG0lnk7ZuCMEKskzdqhKE%2BZidPZj9fAXPw%3D&st=2017-11-07T21%3A15%3A16Z&se=2017-12-08T21%3A20%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711072125299902-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dv2lCIbmGNm%2BVYkMvTjw1lyio7zhzlv1S5gjF%2BQ%2Bp%2FE%3D&st=2017-11-07T21%3A22%3A07Z&se=2017-12-08T21%3A27%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711072136094699-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yF6FryUG9FKNOpk1qCeiyZisF9Bqal0lnaioQTvC4dU%3D&st=2017-11-07T21%3A34%3A03Z&se=2017-12-08T21%3A39%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711072144071881-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xMhkdcYUMR%2BNgMrJHiUiDpHZK%2FEKLID2O64Wh2oUkrI%3D&st=2017-11-07T21%3A41%3A41Z&se=2017-12-08T21%3A46%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/TOC.yml](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/TOC.yml) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-delete-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-delete-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-list-product-offers.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-list-product-offers.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-get-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-get-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-insert-product-offer.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-insert-product-offer.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-example-manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-example-manage-products.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/code-examples.md) | :white_check_mark:Succeeded | |
[BingAds/shopping-content/manage-products.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/content-api-restructure/BingAds/shopping-content/manage-products.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C8%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201711081628155186-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=H8zK126tRgL3XgGr42oeaandsCUK2rCbwIJcq8vf6sA%3D&st=2017-11-08T16%3A25%3A41Z&se=2017-12-09T16%3A30%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brapel** [comment]
#sign-off

**Pull request merged**
