### PR TITLE
Removing space from language delimiter.

### PR DESCRIPTION
**Pull request by benm-brainlabs**
Upload fails if you have a space in the delimiter.

### CODE REVIEW

**Comment by eric-urban** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[BingAds/bingads-12/bulk-service/campaign.md](https://github.com/benm-brainlabs/BingAds-docs/blob/patch-1/BingAds/bingads-12/bulk-service/campaign.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C21%5Ca2e0ab55-2284-a03f-0fb2-0350b6c468ba%5CPullRequest%5C201811211118145560-457%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LUxi%2ByMndBarcAzzN8hrsCKQeW%2B5X1en28g3Oo4K4Yk%3D&st=2018-11-21T11%3A14%3A48Z&se=2018-12-22T11%3A19%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eric-urban** [comment]
@benm-brainlabs thanks for pointing out this issue! Were you prompted to sign a contributor license agreement? (should have been prompted) Since the CLA is not signed I can fix this in a separate commit.

**Comment by benm-brainlabs** [comment]
I was not prompted.

**Comment by eric-urban** [comment]
@benm-brainlabs 

OK I double checked and the CLA will prompt automatically *IF* needed:

All repositories that publish to docs.microsoft.com have adopted the Microsoft Open Source Code of Conduct or the .NET Foundation Code of Conduct. For more information, see the Code of Conduct FAQ. Or contact opencode@microsoft.com, or conduct@dotnetfoundation.org with any questions or comments.

Minor corrections or clarifications to documentation and code examples in public repositories are covered by the docs.microsoft.com Terms of Use. New or significant changes generate a comment in the pull request, asking you to submit an online Contribution License Agreement (CLA) if you are not an employee of Microsoft. We need you to complete the online form before we can review or accept your pull request.

Reference:
https://docs.microsoft.com/en-us/contribute/

In this case the CLA was apparently not needed. Having said that I also noticed the PR you submitted is to merge with 'live' but we should first merge into master. Also there is a merge conflict anyways, and I also have other changes to add, so I'll just go ahead and create a new PR. I will follow up once this page is updated.

**Comment by benm-brainlabs** [comment]
I made the PR into the default place the edit button went? Is it worth making the edit button try and edit master even if it causes a bit of confusion with it being out of sync with live?

**Comment by eric-urban** [comment]
@benm-brainlabs thanks for letting me know! I've reached out to our internal docs.microsoft.com support team for help changing the default PR branch. In the meantime your proposed changes are already live, so I'll go ahead and close this PR. (We also added the list of all languages inline for convenience.)

**Comment by eric-urban** [comment]
@benm-brainlabs just to follow up, master is now the default branch for contributions via the "edit" experience. Thanks again.

**Comment by benm-brainlabs** [comment]
Thanks @eric-urban for the speed!

**Pull request closed without merging**
